[window]
opacity = 1

[terminal]
shell = { program = "/usr/bin/zsh" }

[font]
# Font size - dynamically set by alacritty-launch script
# Laptop (eDP): 12.5, External monitors: 10.0
size = 12.5

[font.normal]
family = "Comic Code"

# Hints for window class identification
[window.class]
instance = "Alacritty"
general = "Alacritty"

# Dark color scheme
[colors.primary]
background = '#000000'
foreground = '#999999'

[colors.normal]
black   = '#45475a'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#bac2de'

[colors.bright]
black   = '#585b70'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#f5c2e7'
cyan    = '#94e2d5'
white   = '#a6adc8'

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
